version: "3"
services:
  app:
    build: ./app
    links:
      - db
    ports:
      - "8080:8080"

  db:
    image: mysql:8.0.21
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: DBSHackGroup12_API
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro